# Width and Height of the project window
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

# Constants for customer class
MIN_INGREDIENTS_REQUESTED = 0
MAX_INGREDIENTS_REQUESTED = 5

# Background screens size and location on the screen
BACKGROUND_SCREENS_X = 0
BACKGROUND_SCREENS_Y = 0
BACKGROUND_SCREENS_WIDTH = WINDOW_WIDTH
BACKGROUND_SCREENS_HEIGHT = WINDOW_HEIGHT

# Main menu button sizes and locations on the screen
START_BUTTON_X = 720
START_BUTTON_Y = 780
START_BUTTON_WIDTH = 1275 - START_BUTTON_X
START_BUTTON_HEIGHT = 980 - START_BUTTON_Y
START_BUTTON_LOCATION = (START_BUTTON_X, START_BUTTON_Y, START_BUTTON_WIDTH, START_BUTTON_HEIGHT)

EXIT_BUTTON_X = 26
EXIT_BUTTON_Y = 26
EXIT_BUTTON_WIDTH = 167 - EXIT_BUTTON_X
EXIT_BUTTON_HEIGHT = 155 - EXIT_BUTTON_Y
EXIT_BUTTON_LOCATION = (EXIT_BUTTON_X, EXIT_BUTTON_Y, EXIT_BUTTON_WIDTH, EXIT_BUTTON_HEIGHT)

# Kosher screen button sizes and locations on the screen
KOSHER_BUTTON_X = 251
KOSHER_BUTTON_Y = 453
KOSHER_BUTTON_WIDTH = 836 - KOSHER_BUTTON_X
KOSHER_BUTTON_HEIGHT = 754 - KOSHER_BUTTON_Y
KOSHER_BUTTON_LOCATION = (KOSHER_BUTTON_X, KOSHER_BUTTON_Y, KOSHER_BUTTON_WIDTH, KOSHER_BUTTON_HEIGHT)

NOT_KOSHER_BUTTON_X = 1082
NOT_KOSHER_BUTTON_Y = 454
NOT_KOSHER_BUTTON_WIDTH = 1665 - NOT_KOSHER_BUTTON_X
NOT_KOSHER_BUTTON_HEIGHT = 754 - NOT_KOSHER_BUTTON_Y
NOT_KOSHER_LOCATION = (NOT_KOSHER_BUTTON_X, NOT_KOSHER_BUTTON_Y, NOT_KOSHER_BUTTON_WIDTH, NOT_KOSHER_BUTTON_HEIGHT)

# Screen movement button sizes and locations on the screen
SCREEN_BUTTON_OFFSET = int(WINDOW_WIDTH / 4)
SCREEN_BUTTON_X = int(WINDOW_WIDTH / 8)
SCREEN_BUTTON_WIDTH = int(WINDOW_WIDTH / 10)
SCREEN_BUTTON_HEIGHT = int(WINDOW_HEIGHT / 10)
SCREEN_BUTTON_Y = WINDOW_WIDTH - SCREEN_BUTTON_HEIGHT
SCREEN_BUTTON_CUSTOMER_LOCATION = (SCREEN_BUTTON_X, SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)
SCREEN_BUTTON_PRECOOKING_LOCATION = (SCREEN_BUTTON_X + SCREEN_BUTTON_OFFSET, SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)
SCREEN_BUTTON_COOKING_LOCATION = (SCREEN_BUTTON_X + (SCREEN_BUTTON_OFFSET * 2), SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)
SCREEN_BUTTON_FINISHING_LOCATION = (SCREEN_BUTTON_X + (SCREEN_BUTTON_OFFSET * 3), SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)

# First stage locations
TAKE_ORDER_X_POS = 196
TAKE_ORDER_Y_POS = 156
TAKE_ORDER_BUTTON_LOCATION = (210, 180, 90, 45)
