# Width and Height of the project window
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

# Constants for customer class
MIN_INGREDIENTS_REQUESTED = 0
MAX_INGREDIENTS_REQUESTED = 5

# Background screens size and location on the screen
BACKGROUND_SCREENS_X = 0
BACKGROUND_SCREENS_Y = 0
BACKGROUND_SCREENS_WIDTH = WINDOW_WIDTH
BACKGROUND_SCREENS_HEIGHT = WINDOW_HEIGHT

# Main menu button sizes and locations on the screen
START_BUTTON_X = 720
START_BUTTON_Y = 780
START_BUTTON_WIDTH = 1275 - START_BUTTON_X
START_BUTTON_HEIGHT = 980 - START_BUTTON_Y
START_BUTTON_LOCATION = (START_BUTTON_X, START_BUTTON_Y, START_BUTTON_WIDTH, START_BUTTON_HEIGHT)

EXIT_BUTTON_X = 26
EXIT_BUTTON_Y = 26
EXIT_BUTTON_WIDTH = 167 - EXIT_BUTTON_X
EXIT_BUTTON_HEIGHT = 155 - EXIT_BUTTON_Y
EXIT_BUTTON_LOCATION = (EXIT_BUTTON_X, EXIT_BUTTON_Y, EXIT_BUTTON_WIDTH, EXIT_BUTTON_HEIGHT)

# Kosher screen button sizes and locations on the screen
KOSHER_BUTTON_X = 251
KOSHER_BUTTON_Y = 453
KOSHER_BUTTON_WIDTH = 836 - KOSHER_BUTTON_X
KOSHER_BUTTON_HEIGHT = 754 - KOSHER_BUTTON_Y
KOSHER_BUTTON_LOCATION = (KOSHER_BUTTON_X, KOSHER_BUTTON_Y, KOSHER_BUTTON_WIDTH, KOSHER_BUTTON_HEIGHT)

NOT_KOSHER_BUTTON_X = 1082
NOT_KOSHER_BUTTON_Y = 454
NOT_KOSHER_BUTTON_WIDTH = 1665 - NOT_KOSHER_BUTTON_X
NOT_KOSHER_BUTTON_HEIGHT = 754 - NOT_KOSHER_BUTTON_Y
NOT_KOSHER_LOCATION = (NOT_KOSHER_BUTTON_X, NOT_KOSHER_BUTTON_Y, NOT_KOSHER_BUTTON_WIDTH, NOT_KOSHER_BUTTON_HEIGHT)

# Screen movement button sizes and locations on the screen
SCREEN_BUTTON_OFFSET = 35
SCREEN_BUTTON_X = 464
SCREEN_BUTTON_Y = 965
SCREEN_BUTTON_WIDTH = 700 - SCREEN_BUTTON_X
SCREEN_BUTTON_HEIGHT = 1064 - SCREEN_BUTTON_Y
SCREEN_BUTTON_ORDER_LOCATION = (SCREEN_BUTTON_X, SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)
SCREEN_BUTTON_BREAD_LOCATION = (SCREEN_BUTTON_X + SCREEN_BUTTON_WIDTH + SCREEN_BUTTON_OFFSET, SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)
SCREEN_BUTTON_COOKING_LOCATION = (SCREEN_BUTTON_X + 2 * (SCREEN_BUTTON_WIDTH + SCREEN_BUTTON_OFFSET), SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)
SCREEN_BUTTON_TOPPING_LOCATION = (SCREEN_BUTTON_X + 3 * (SCREEN_BUTTON_WIDTH + SCREEN_BUTTON_OFFSET), SCREEN_BUTTON_Y, SCREEN_BUTTON_WIDTH, SCREEN_BUTTON_HEIGHT)

# Queue stage locations
TAKE_ORDER_X = 196
TAKE_ORDER_Y = 156
TAKE_ORDER_BUTTON_LOCATION = (210, 180, 90, 45)

# Order
ORDER_SIZE = (190, 300)
ORDER_POS = (601, 6)

# Topping station
LEFT_TOPPINGS_X_POS = 275
LEFT_TOPPINGS_Y_POS = 475
TOPPINGS_OFFSET = 80
TOPPING_WIDTH = 240
TOPPING_HEIGHT = 100
